language: haskell
install:
  - cabal update
  - cabal install --only-dep --enable-tests
  - cabal install hpc-coveralls
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build
  - run-cabal-test
  - cd example
  - cabal install
  - cd ..
after_script:
  - hpc-coveralls --exclude-dir=test test
