resolver: lts-7.1

packages:
- '.'
- location:
    git: https://github.com/snapframework/snap-loader-static.git
    commit: 75e8d0a8d725332098ea779a6e2995cc7b8e31fb  
- example/

extra-deps:
   - template-haskell-2.10.0.0   
   - map-syntax-0.2.0.1
   - heist-1.0.0.0
   - snap-1.0.0.1
   - aeson-0.11.1.4
   - base-orphans-0.5.4
   - clock-0.7.2
   - text-1.2.2.1
   
flags: {}
extra-package-dbs: []
