resolver: lts-7.3

packages:
- '.'
- example/

extra-deps:
   - template-haskell-2.10.0.0   
   - map-syntax-0.2.0.1
   - heist-1.0.0.0
   - snap-1.0.0.1
   - snap-loader-static-1.0.0.0
   - aeson-0.11.1.4
   - base-orphans-0.5.4
   - clock-0.7.2
   - text-1.2.2.1
   
flags: {}
extra-package-dbs: []
